name: Docker - CI

on:
  push:
    branches: [ 'main' ]
    tags-ignore: [ '**' ]
    paths: [ 'docker/**', '.github/workflows/docker-ci.yml' ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible-version: [ '11.10.0' ]

    steps:

      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ matrix.ansible-version }}-preview
            type=sha,prefix=${{ matrix.ansible-version }}-,suffix=-preview,format=short

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ANSIBLE_VERSION=${{ matrix.ansible-version }}
