name: Docker - Release

on:
  push:
    tags: [ '*.*.*' ]

permissions:
  contents: read
  packages: write

jobs:
  registry:
    name: GitHub Container Registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible-version: [ '12.0.0', '11.10.0', '10.7.0' ]

    steps:

      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ matrix.ansible-version }}
            type=raw,value=${{ matrix.ansible-version }}-${{ github.ref_name }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ANSIBLE_VERSION=${{ matrix.ansible-version }}
